# Fluid Configuration
## Manual: https://hexo.fluid-dev.com/docs/guide/

# About Page
about:
  avatar: /images/common/avatar.png
  name: "Ivy(Yiting) Liu"
  intro: "An Innovative Software Engineer"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
    - { class: 'iconfont icon-linkedin-fill', link: 'https://www.linkedin.com/in/yiting-ivy-liu/', tip: 'LinkedIn' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/images/common/WechatQR.jpg' }

# Navigate Bar
navbar:
  blog_title: Ivy's Blog

# Index Page
index:
  slogan:
    enable: true
    text: Welcome to Ivy's Blog
