# Fluid Configuration
## Manual: https://hexo.fluid-dev.com/docs/guide/

# About Page
about:
  avatar: /img/avatar.png
  name: "Fluid"
  intro: "An elegant for Hexo"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
    - { class: 'iconfont icon-douban-fill', link: 'https://douban.com', tip: '豆瓣' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }