name: CI

on:
  push:
    branches: ["main"]

env:
  GIT_USER: ivyliu1205
  GIT_EMAIL: ivy1205liu@gmail.com
  THEME_REPO: ivyliu1205/ivyliu1205.github.io
  THEME_BRANCH: main
  DEPLOY_REPO: ivyliu1205/ivyliu1205.github.io
  DEPLOY_BRANCH: main

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install hexo
        run: |
          npm install hexo-cli -g
          npm ci
      
      # - name: Install fluid
      #   run: npm install --save hexo-theme-fluid
        
      - name: Install npm
        run: npm install

      - name: Deploy hexo 
        run: |
          hexo clean
          hexo g
          hexo d
          ls -R public/
